### ISSUE TITLE
Problem in installing on Python 3.4.0 on Windows 7

### ISSUE THREAD

**Issue by anshbansal** [kivy-garden/garden.filebrowser#6]
I was trying to install filebrowser on Python 3.4 using powershell on windows 7 and got this problem. Any ideas why?

PS D:\study\kivy_designer> garden install filebrowser

D:\study\kivy_designer>python.exe C:\Python34\Scripts\garden install filebrowser
Downloading http://github.com/kivy-garden/garden.filebrowser/archive/master.zip ...
Traceback (most recent call last):
  File "C:\Python34\Scripts\garden", line 189, in <module>
    GardenTool().main(sys.argv[1:])
  File "C:\Python34\Scripts\garden", line 71, in main
    options.func()
  File "C:\Python34\Scripts\garden", line 109, in cmd_install
    fd = self.download(opts.package)
  File "C:\Python34\Scripts\garden", line 170, in download
    data += buf
TypeError: Can't convert 'bytes' object to str implicitly

**Comment by matham** [comment]
I believe the garden tool has already been fixed.
